---
- name: "Remove any deleted DNS A records"
  nsupdate:
    key_name: "{{ item.0.key_name }}"
    key_secret: "{{ item.0.key_secret }}"
    key_algorithm: "{{ item.0.key_algorithm }}"
    server: "{{ item.0.server }}"
    zone: "{{ item.0.zone }}"
    record: "{{ item.1.hostname }}"
    type: "{{ item.1.type }}"
    state: absent
  with_subelements:
  - "{{ dns_records_rm | default({}) }}"
  - entries

- name: "Add DNS A records"
  nsupdate:
    key_name: "{{ item.0.key_name }}"
    key_secret: "{{ item.0.key_secret }}"
    key_algorithm: "{{ item.0.key_algorithm }}"
    server: "{{ item.0.server }}"
    zone: "{{ item.0.zone }}"
    record: "{{ item.1.hostname }}"
    value: "{{ item.1.ip }}"
    type: "{{ item.1.type }}"
    state: present
  with_subelements:
  - "{{ dns_records_add | default({}) }}"
  - entries
  register: nsupdate_result
  until: nsupdate_result.dns_rc == 0
  retries: 10
  delay: 1
